Repository bmstu-iu9/utp2020-1-chat, pull requests merged in 2020-08, with the labels that each got.

#30 Logo
  Media/LOGO.jpg
  Media/about.png
  Media/back.png
  Media/back11.psd
  Media/background.png
  Media/div.png
  Media/eye-closed.png
  Media/eye-opened.png
  Media/logo.jpg
  Media/logo1.png
  Media/settings.png
  README.md
Labels: documentation, enhancement

#32 Выполнение вопроса #31
  Media/MainLogo.jpg
  README.md
Labels: bug

#38 Всплывающее раскрывающееся меню
  Data/Menu/index.html
  Data/Menu/media/logout.png
  Data/Menu/media/open-menu.png
  Data/Menu/media/фон образец.jpg
  Data/Menu/scripts/pop-up.js
  Data/Menu/styles/menu.css
Labels: enhancement

#39 Перенос "глаза" в окно ввода пароля
  Data/Login/index.html
  Data/Login/scripts/eye-opener.js
  Data/Login/styles/login.css
  Data/Registration/index.html
  Data/Registration/scripts/eye-opener.js
  Data/Registration/scripts/validation.js
  Data/Registration/styles/registration.css
Labels: bug, enhancement

#66 Дополнение README
  MainLogo.jpg
  Media/about.png
  Media/back.png
  Media/back11.psd
  Media/background.png
  Media/div.png
  Media/eye-closed.png
  Media/eye-opened.png
  Media/logo.jpg
  Media/logo1.png
  Media/settings.png
  README.md
Labels: documentation

#67 Изменение дизайна страницы чата/комнаты
  Data/Chat/Media/about.png
  Data/Chat/Media/background.png
  Data/Chat/Media/leave.png
  Data/Chat/Media/logo.png
  Data/Chat/Media/logout.png
  Data/Chat/Media/open-menu.png
  Data/Chat/Media/plus-gray.png
  Data/Chat/Media/search.png
  Data/Chat/Media/settings.png
  Data/Chat/index.html
  Data/Chat/scripts/pop-up.js
  Data/Chat/scripts/toolbar.js
  Data/Chat/scripts/users.js
  Data/Chat/styles/chat.css
Labels: enhancement

#81 Добавлены emoji
  Chat/pages/chat.ejs
  Chat/public/scripts/add-emoji.js
  Chat/public/scripts/show-emoji.js
  Chat/public/styles/chat.css
Labels: enhancement

#83 Обновление README
  README.md
Labels: documentation
